/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jxb_testjni_TestJni */

#ifndef _Included_com_example_jxb_testjni_TestJni
#define _Included_com_example_jxb_testjni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jxb_testjni_TestJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jxb_testjni_TestJni_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
